### PR TITLE
Fixes for signs in 1.20, dependency/lintings updates

### PR DESCRIPTION
**Pull request by N6UDP**
* Fixes handling of signs in Minecraft 1.20+ (they changed the NBT for them fairly significantly)
  * This does break previous version of MC but the docker container is on 1.20.4 today
* Updates ipython to 8.20
  * Adds a venv related hack - I couldn't figure out why tox fails with that venv warning/erro but pytest doesn't - disabling it in the test execution path works but is ugly :/
* setting.json update / other whitespace changes seem to be due to vscode / linting changes/updates

### CODE REVIEW

**Comment by gilesknap** [comment]
This is great, thanks! Inspires me to get back into this project.

Do you want to take a look at why the CI is failing? I could take a look this weekend if not.

**Comment by gilesknap** [comment]
I have invited you as a collaborator so you can look at the CI if you wish.

I'm OK with only supporting the later versions of Minecraft - the goal of this project is to have fun with python and it would be pretty hard to support all versions of  MC.

BTW, it would be interesting to look into what else has changed re NBT. I found that signs were about the most useful thing for creating an interactive interface because they had the most rich NBT but perhaps there are better choices now.  Also, I think I recall that I have to constantly poll a range of blocks for the sign, it would be better if a search were available through the API but I never found such a thing (witness the clunky workaround for get_block https://github.com/mcipc-tools/mcwb/blob/96c16003d6365a4d017d82a62ce06b4677f95fe6/mcwb/api.py#L78-L96).

**Comment by N6UDP** [comment]
"Fixed" some of the CI by pinning the python version (seems broken due to disttools deprecation in 3.12 see https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated ).
Not entirely sure what's up with the permission denied error coming from the test_backup which works locally but not on actions.  I did try moving from /tmp to $HOME but that didn't make a difference.
FWIW speaking of updates/changes in MC: https://github.com/conqp/mcipc/commit/c231c63cf1611a7f324799cf3949485d27956b94

**Comment by gilesknap** [comment]
Looks Good. Merging.

re the v4 artifact action. This is fixed in the skeleton so is just the kind of thing that using skeleton is good for. I also think we are dropping the whole upload publishing of requirements.txt thing as too cumbersome. To be replaced by the use of a constraints file and dependabot.

**Comment by gilesknap** [comment]
just a headsup: @N6UDP don't do any more work on the CI - I'm pulling in our latest copier project which will rewrite all of the CI.

**Pull request merged**
